/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAttribute: typeof import('./../components/products/attributes/AddAttribute.vue')['default']
    AddCategory: typeof import('./../components/products/categories/AddCategory.vue')['default']
    AddMenu: typeof import('./../components/menu/AddMenu.vue')['default']
    AddPermission: typeof import('./../components/Permission/AddPermission.vue')['default']
    AddProduct: typeof import('./../components/products/AddProduct.vue')['default']
    AddRole: typeof import('./../components/Role/AddRole.vue')['default']
    AddShop: typeof import('./../components/shop/AddShop.vue')['default']
    AddUser: typeof import('./../components/users/AddUser.vue')['default']
    AddVariant: typeof import('./../components/products/variants/AddVariant.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    EditAttribute: typeof import('./../components/products/attributes/EditAttribute.vue')['default']
    EditCategory: typeof import('./../components/products/categories/EditCategory.vue')['default']
    EditMenu: typeof import('./../components/menu/EditMenu.vue')['default']
    EditPermission: typeof import('./../components/Permission/EditPermission.vue')['default']
    EditProduct: typeof import('./../components/products/EditProduct.vue')['default']
    EditRole: typeof import('./../components/Role/EditRole.vue')['default']
    EditShop: typeof import('./../components/shop/EditShop.vue')['default']
    EditUser: typeof import('./../components/users/EditUser.vue')['default']
    EditVariant: typeof import('./../components/products/variants/EditVariant.vue')['default']
    GlobalLoading: typeof import('./../components/GlobalLoading/index.vue')['default']
    MultiImageUploader: typeof import('./../components/upload/MultiImageUploader/MultiImageUploader.vue')['default']
    PermissionSelector: typeof import('./../components/Permission/PermissionSelector.vue')['default']
    ProductGeneralInfo: typeof import('./../components/products/components/ProductGeneralInfo.vue')['default']
    ProductVariants: typeof import('./../components/products/components/ProductVariants.vue')['default']
    RoleSelector: typeof import('./../components/Role/RoleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleAttributeSelector: typeof import('./../components/products/attributes/SingleAttributeSelector.vue')['default']
    SingleCategorySelector: typeof import('./../components/products/categories/selector/SingleCategorySelector.vue')['default']
    SingleImageUploader: typeof import('./../components/upload/SingleImageUploader/SingleImageUploader.vue')['default']
    SingleRoleSelector: typeof import('./../components/Role/SingleRoleSelector.vue')['default']
    SingleShopSelector: typeof import('./../components/shop/selector/SingleShopSelector.vue')['default']
    ThemeSwitchDevTool: typeof import('./../components/ThemeSwitchDevTool/index.vue')['default']
  }
}
